name: Test

on:
  push:
    branches: [ main, initial-js-v2 ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        
    - name: Install and test
      run: |
        npm install
        npm test